// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type FetchOrdersDto = {
    /**
     * Start date for fetching orders (ISO date string)
     */
    since?: string;
    /**
     * End date for fetching orders (ISO date string)
     */
    until?: string;
    /**
     * Trading pair to filter orders (e.g., BTC-USDT)
     */
    pair?: string;
    /**
     * Exchange ID to fetch orders from
     */
    exchange?: string;
    /**
     * Compute performance
     */
    computePerformance?: boolean;
};

export type CreateRuleDto = {
    /**
     * Unique identifier for the rule
     */
    uid: string;
    /**
     * Whether the rule is active
     */
    active?: boolean;
    /**
     * Trading pair for the rule
     */
    pair: string;
    /**
     * Market type
     */
    market: string;
    /**
     * Timeframe for price data (fallback for activators without explicit timeframe)
     */
    timeframe: string;
    /**
     * Type of data fetch
     */
    fetchType: string;
    /**
     * Array of rule activators (conditions). All must match for the rule to trigger.
     */
    activators: Array<unknown>;
    /**
     * Array of actions to execute when all activators match
     */
    actions: Array<unknown>;
    /**
     * Array of deadlines (optional)
     */
    deadlines?: Array<unknown>;
};

export type UpdateRuleDto = {
    /**
     * Whether the rule is active
     */
    active?: boolean;
    /**
     * Trading pair for the rule
     */
    pair?: string;
    /**
     * Market type
     */
    market?: string;
    /**
     * Timeframe for price data
     */
    timeframe?: string;
    /**
     * Type of data fetch
     */
    fetchType?: string;
    /**
     * Array of rule activators (conditions)
     */
    activators?: Array<unknown>;
    /**
     * Array of actions to execute when rule is activated
     */
    actions?: Array<unknown>;
    /**
     * Array of deadlines (optional)
     */
    deadlines?: Array<unknown>;
};

export type LoginDto = {
    [key: string]: unknown;
};

export type AppControllerHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppControllerHealthResponses = {
    200: unknown;
};

export type ApiOrderControllerFetchOrdersData = {
    body: FetchOrdersDto;
    path?: never;
    query?: never;
    url: '/api/orders';
};

export type ApiOrderControllerFetchOrdersResponses = {
    /**
     * Orders retrieved successfully
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiOrderControllerFetchOrdersResponse = ApiOrderControllerFetchOrdersResponses[keyof ApiOrderControllerFetchOrdersResponses];

export type ApiRulesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rules';
};

export type ApiRulesControllerFindAllResponses = {
    /**
     * List of all rules
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ApiRulesControllerFindAllResponse = ApiRulesControllerFindAllResponses[keyof ApiRulesControllerFindAllResponses];

export type ApiRulesControllerCreateData = {
    body: CreateRuleDto;
    path?: never;
    query?: never;
    url: '/api/rules';
};

export type ApiRulesControllerCreateResponses = {
    /**
     * Rule created successfully
     */
    201: unknown;
};

export type ApiRulesControllerFindActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rules/active';
};

export type ApiRulesControllerFindActiveResponses = {
    /**
     * List of active rules
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ApiRulesControllerFindActiveResponse = ApiRulesControllerFindActiveResponses[keyof ApiRulesControllerFindActiveResponses];

export type ApiRulesControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Rule unique identifier
         */
        uid: string;
    };
    query?: never;
    url: '/api/rules/{uid}';
};

export type ApiRulesControllerRemoveResponses = {
    /**
     * Rule deleted successfully
     */
    204: void;
};

export type ApiRulesControllerRemoveResponse = ApiRulesControllerRemoveResponses[keyof ApiRulesControllerRemoveResponses];

export type ApiRulesControllerFindOneData = {
    body?: never;
    path: {
        /**
         * Rule unique identifier
         */
        uid: string;
    };
    query?: never;
    url: '/api/rules/{uid}';
};

export type ApiRulesControllerFindOneErrors = {
    /**
     * Rule not found
     */
    404: unknown;
};

export type ApiRulesControllerFindOneResponses = {
    /**
     * Rule found
     */
    200: unknown;
};

export type ApiRulesControllerUpdateData = {
    body: UpdateRuleDto;
    path: {
        /**
         * Rule unique identifier
         */
        uid: string;
    };
    query?: never;
    url: '/api/rules/{uid}';
};

export type ApiRulesControllerUpdateResponses = {
    /**
     * Rule updated successfully
     */
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Returns JWT access token
     */
    200: unknown;
};
