// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiOrderControllerFetchOrdersData, ApiOrderControllerFetchOrdersResponses, ApiRulesControllerCreateData, ApiRulesControllerCreateResponses, ApiRulesControllerFindActiveData, ApiRulesControllerFindActiveResponses, ApiRulesControllerFindAllData, ApiRulesControllerFindAllResponses, ApiRulesControllerFindOneData, ApiRulesControllerFindOneErrors, ApiRulesControllerFindOneResponses, ApiRulesControllerRemoveData, ApiRulesControllerRemoveResponses, ApiRulesControllerUpdateData, ApiRulesControllerUpdateResponses, AppControllerHealthData, AppControllerHealthResponses, AuthControllerLoginData, AuthControllerLoginErrors, AuthControllerLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerHealth = <ThrowOnError extends boolean = false>(options?: Options<AppControllerHealthData, ThrowOnError>) => (options?.client ?? client).get<AppControllerHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Fetch orders from exchange
 *
 * Retrieves orders from the specified exchange, optionally filtered by date range and trading pair
 */
export const apiOrderControllerFetchOrders = <ThrowOnError extends boolean = false>(options: Options<ApiOrderControllerFetchOrdersData, ThrowOnError>) => (options.client ?? client).post<ApiOrderControllerFetchOrdersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/orders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all trading rules
 */
export const apiRulesControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<ApiRulesControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<ApiRulesControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rules',
    ...options
});

/**
 * Create a new trading rule
 */
export const apiRulesControllerCreate = <ThrowOnError extends boolean = false>(options: Options<ApiRulesControllerCreateData, ThrowOnError>) => (options.client ?? client).post<ApiRulesControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rules',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all active trading rules
 */
export const apiRulesControllerFindActive = <ThrowOnError extends boolean = false>(options?: Options<ApiRulesControllerFindActiveData, ThrowOnError>) => (options?.client ?? client).get<ApiRulesControllerFindActiveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rules/active',
    ...options
});

/**
 * Delete a trading rule
 */
export const apiRulesControllerRemove = <ThrowOnError extends boolean = false>(options: Options<ApiRulesControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<ApiRulesControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rules/{uid}',
    ...options
});

/**
 * Get a trading rule by UID
 */
export const apiRulesControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<ApiRulesControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<ApiRulesControllerFindOneResponses, ApiRulesControllerFindOneErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rules/{uid}',
    ...options
});

/**
 * Update a trading rule
 */
export const apiRulesControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiRulesControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<ApiRulesControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rules/{uid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login with username and password
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginResponses, AuthControllerLoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
